<table width="80%" border="1">
  <tr>
    <td>Student Id</td>
    <td>Class Roll</td>
    <td>Month</td>
    <td>Working Day</td>
    <td>Present</td>
    <td>Absent</td>
  </tr>
  <tr>
    <td>1114</td>
    <td>1</td>
    <td>January</td>
    <td>22</td>
    <td>20</td>
    <td>2</td>
  </tr>
  <tr>
    <td>1114</td>
    <td>1</td>
    <td>Febuary</td>
    <td>25</td>
    <td>20</td>
    <td>5</td>
  </tr>
  <tr>
    <td>1114</td>
    <td>1</td>
    <td>March</td>
    <td>27</td>
    <td>18</td>
    <td>9</td>
  </tr>
  <tr>
    <td>1114</td>
    <td>1</td>
    <td>April</td>
    <td>22</td>
    <td>20</td>
    <td>2</td>
  </tr>
    <tr>
    <td>1114</td>
    <td>1</td>
    <td>May</td>
    <td>10</td>
    <td>10</td>
    <td>0</td>
  </tr>
  <tr>
    <td>1114</td>
    <td>1</td>
    <td>Jun</td>
    <td>22</td>
    <td>20</td>
    <td>2</td>
  </tr>
    <tr>
    <td>1114</td>
    <td>1</td>
    <td>Julay</td>
    <td>19</td>
    <td>17</td>
    <td>2</td>
  </tr>
  <tr>
    <td>1114</td>
    <td>1</td>
    <td>August</td>
    <td>22</td>
    <td>20</td>
    <td>2</td>
  </tr>
    <tr>
    <td>1114</td>
    <td>1</td>
    <td>September</td>
    <td>23</td>
    <td>20</td>
    <td>3</td>
  </tr>
  <tr>
    <td>1114</td>
    <td>1</td>
    <td>October</td>
    <td>22</td>
    <td>20</td>
    <td>2</td>
  </tr>
    <tr>
    <td>1114</td>
    <td>1</td>
    <td>Novemer</td>
    <td>22</td>
    <td>20</td>
    <td>2</td>
  </tr>
  <tr>
    <td>1114</td>
    <td>1</td>
    <td>December</td>
    <td>22</td>
    <td>20</td>
    <td>2</td>
  </tr>
  <tr>
    <td>1114</td>
    <td>1</td>
    <td>Total Month</td>
    <td>300&nbsp;Day</td>
    <td>260</td>
    <td>20</td>
  </tr>
  
  </table>
