<?php
session_start();
include_once("DAL/DbConnect.php");
include_once("DAL/dalStudent.php");
include_once("DAL/dalTeacher.php");
include_once("DAL/dalAcademicCalender.php");
include_once("DAL/dalClass.php");
include_once("DAL/dalClassBlog.php");
include_once("DAL/dalYear.php");
include_once("DAL/dalAssigningSubjectAndTeacher.php");
include_once("DAL/dalSection.php");
include_once("DAL/dalShift.php");
include_once("DAL/dalExamName.php");
include_once("DAL/dalSubject.php");
include_once("DAL/dalIqtest.php");
include_once("DAL/dalClassMaterial.php");
include_once("DAL/dalAdministration.php");
include_once("DAL/dalGardianMember.php");
include_once("DAL/dalNoticBord.php");
include_once("DAL/dalHomeWelcome.php");
include_once("DAL/dalPhotoGallary.php");
include_once("DAL/dalPhotoSlider.php");
include_once("DAL/dalSubjectQuestion.php");
include_once("DAL/dalAcademicCalenderType.php");
include_once("DAL/dalPhotoType.php");
include_once("DAL/dalClassMaterialType.php");
include_once("DAL/dalNoticType.php");
include_once("DAL/dalCommonBlog.php");
include_once("DAL/dalAssingingTeacher.php");
include_once("DAL/dalNews.php");
include_once("DAL/dalAboutUs.php");
include_once("DAL/dalContactUsUser.php");
include_once("DAL/dalUsefullink.php");
include_once("DAL/dalUpComingEvent.php");
include_once("DAL/dalContactUs.php");
include_once("DAL/dalSchoolContact.php");
include_once("DAL/dalResult.php");
include_once("DAL/dalReligion.php");
include_once("DAL/dalBloodGroup.php");
include_once("DAL/dalWaiver.php");
include_once("DAL/dalPayOrPaidAmountType.php");
include_once("DAL/dalPayableAmount.php");
include_once("DAL/dalPaidAmount.php");
include_once("DAL/dalMonth.php");
include_once("DAL/dalDay.php");

include_once("DAL/dalEarn.php");
include_once("DAL/dalEarnType.php");
include_once("DAL/dalExpence.php");
include_once("DAL/dalExpenceType.php");
include_once("DAL/dalExpenceForPublishType.php");
include_once("DAL/dalExpenceForPublish.php");
include_once("DAL/dalExpenceForGardiantArrangementType.php");
include_once("DAL/dalExpenceForGardiantArrangement.php");
include_once("DAL/dalTeacherAccountInfo.php");
include_once("DAL/dalTypeTeacher.php");
include_once("DAL/dalAssigningClassForStudent.php");


include_once("controller/function.php");

?>